# Generated by Django 3.1.3 on 2020-12-29 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='moviePreference',
        ),
        migrations.AddField(
            model_name='request',
            name='createdDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='statusChangeDate',
            field=models.DateField(null=True),
        ),
    ]
