# Generated by Django 3.1.3 on 2020-12-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0002_auto_20201229_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematching',
            name='referenceRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singleMatching', to='hola.request'),
        ),
        migrations.AlterField(
            model_name='singlematching',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='hola.profile'),
        ),
    ]
