# Generated by Django 3.1.3 on 2020-12-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0003_auto_20201229_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'accpeted'), ('3', 'rejected')], default='1', max_length=50),
        ),
    ]
