# Generated by Django 3.1.3 on 2020-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0004_auto_20201230_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accpeted'), ('rejected', 'rejected')], default='1', max_length=50),
        ),
    ]
