# Generated by Django 3.1.3 on 2021-01-05 10:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0006_auto_20210105_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
