# Generated by Django 3.1.3 on 2021-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0007_auto_20210105_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moviePreference',
            field=models.TextField(null=True),
        ),
    ]
